--ESQUEMA DE LA BASE DE DATOS

CREATE TABLE ROLE
(
ID_ROLE INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
ROLE_NAME VARCHAR(20) NOT NULL CHECK(ROLE_NAME IN('ADMIN','CLIENT')) UNIQUE,
ROLE_CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
)
CREATE TABLE USER_INFO
(
ID_USER_INFO INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
FIRST_NAME VARCHAR(100) NOT NULL,
LAST_NAME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(200) NULL,
PHONE_NUMBER VARCHAR(15) NOT NULL
)

CREATE TABLE USERGREEN
(
ID_USER INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
USERNAME VARCHAR(50) NOT NULL UNIQUE,
USERPASSWORD VARCHAR(200) NOT NULL,
USER_CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
USER_STATUS TINYINT(1) NOT NULL CHECK(USER_STATUS IN(1,0)),
ID_USER_INFO INT NOT NULL,
ID_ROLE INT NOT NULL,
FOREIGN KEY(ID_ROLE) REFERENCES ROLE(ID_ROLE),
FOREIGN KEY(ID_USER_INFO) REFERENCES USER_INFO(ID_USER_INFO)
)

CREATE TABLE IMAGES
(
ID_IMAGE INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
IMAGE_PATH TEXT NOT NULL,
UPLOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
ID_USER INT NOT NULL,
FOREIGN KEY(ID_USER) REFERENCES USERGREEN(ID_USER)
)